name: Diff Test Suite Agent
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop, test]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run diff test suite agent
        uses: qodo-ai/qodo-gen-cli@v1
        env:
          QODO_API_KEY: ${{ secrets.QODO_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prompt: diff-test-suite
          agent-file: agent.toml
          key-value-pairs: |
            base_branch=test
            files_to_ignore=package-lock.json,*.md
            run_tests=true
